<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Tweet;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $maxresults
     * @return array
     */
    public function getLastTweets($maxresults = 10){
        return $this->createQueryBuilder('t')
                    ->select('t')
                    ->setMaxResults($maxresults)
                    ->orderBy('t.createdAt', 'DESC')
                    ->getQuery()
                    ->getResult();
    }


    /**
     * @param $id
     * @return Tweet
     */
    public function getTweet($id){
        return $this->createQueryBuilder('t')
                    ->select('t')
                    ->andWhere('t.id = :id')
                    ->setParameter('id', $id)
                    ->getQuery()
                    ->getOneOrNullResult();
    }
}
